package man.iab.proxy;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

public class BejacnSessionBeanServicePortClient
{
  @WebServiceRef
  private static BejacnSessionBeanService_Service bejacnSessionBeanService_Service;

  public static void main(String [] args)
  {
    bejacnSessionBeanService_Service = new BejacnSessionBeanService_Service();
    BejacnSessionBeanService bejacnSessionBeanService = bejacnSessionBeanService_Service.getBejacnSessionBeanServicePort();
    // Add your code to call the desired methods.
  }
}
