package man.ias.proxy;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebService(wsdlLocation="http://10.204.6.247:8100/StmtBrokerSessionBean/StmtBrokerSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ias.man%2F%7DStmtBrokerSessionBeanService?wsdl",
  targetNamespace="http://session.ias.man/", name="StmtBrokerSessionBeanService")
@XmlSeeAlso(
  { man.ias.proxy.types.ObjectFactory.class })
public interface StmtBrokerSessionBeanService
{
  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="getStmtBrokerFindByLimitResponse",
    targetNamespace="http://session.ias.man/", className="man.ias.proxy.types.GetStmtBrokerFindByLimitResponse")
  @RequestWrapper(localName="getStmtBrokerFindByLimit", targetNamespace="http://session.ias.man/",
    className="man.ias.proxy.types.GetStmtBrokerFindByLimit")
  @WebResult(targetNamespace="")
  public List<man.ias.proxy.types.StmtBroker> getStmtBrokerFindByLimit(@WebParam(targetNamespace="",
      name="kodeAb")
    String kodeAb);

  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="updateStmtBrokerSetFlagResponse",
    targetNamespace="http://session.ias.man/", className="man.ias.proxy.types.UpdateStmtBrokerSetFlagResponse")
  @RequestWrapper(localName="updateStmtBrokerSetFlag", targetNamespace="http://session.ias.man/",
    className="man.ias.proxy.types.UpdateStmtBrokerSetFlag")
  @WebResult(targetNamespace="")
  public int updateStmtBrokerSetFlag(@WebParam(targetNamespace="", name="kodeAb")
    String kodeAb, @WebParam(targetNamespace="", name="extref")
    String extref, @WebParam(targetNamespace="", name="acctno")
    String acctno, @WebParam(targetNamespace="", name="valdate")
    String valdate, @WebParam(targetNamespace="", name="seqnum")
    long seqnum, @WebParam(targetNamespace="", name="trnref")
    String trnref);
}
