package man.ias.proxy;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebServiceClient(wsdlLocation="http://10.204.6.247:8100/StmtBrokerSessionBean/StmtBrokerSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ias.man%2F%7DStmtBrokerSessionBeanService?wsdl",
  targetNamespace="http://session.ias.man/", name="StmtBrokerSessionBeanService")
public class StmtBrokerSessionBeanService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("man.ias.proxy.StmtBrokerSessionBeanService_Service");
      URL baseUrl =
        StmtBrokerSessionBeanService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            StmtBrokerSessionBeanService_Service.class.getResource("http://10.204.6.247:8100/StmtBrokerSessionBean/StmtBrokerSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ias.man%2F%7DStmtBrokerSessionBeanService?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://10.204.6.247:8100/StmtBrokerSessionBean/StmtBrokerSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ias.man%2F%7DStmtBrokerSessionBeanService?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://10.204.6.247:8100/StmtBrokerSessionBean/StmtBrokerSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ias.man%2F%7DStmtBrokerSessionBeanService?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://10.204.6.247:8100/StmtBrokerSessionBean/StmtBrokerSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ias.man%2F%7DStmtBrokerSessionBeanService?wsdl",
          e);
    }
  }

  public StmtBrokerSessionBeanService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://session.ias.man/", "StmtBrokerSessionBeanService"));
  }

  public StmtBrokerSessionBeanService_Service(URL wsdlLocation,
                                              QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="StmtBrokerSessionBeanServicePort")
  public man.ias.proxy.StmtBrokerSessionBeanService getStmtBrokerSessionBeanServicePort()
  {
    return (man.ias.proxy.StmtBrokerSessionBeanService) super.getPort(new QName("http://session.ias.man/",
                                                                                "StmtBrokerSessionBeanServicePort"),
                                                                      man.ias.proxy.StmtBrokerSessionBeanService.class);
  }

  @WebEndpoint(name="StmtBrokerSessionBeanServicePort")
  public man.ias.proxy.StmtBrokerSessionBeanService getStmtBrokerSessionBeanServicePort(WebServiceFeature... features)
  {
    return (man.ias.proxy.StmtBrokerSessionBeanService) super.getPort(new QName("http://session.ias.man/",
                                                                                "StmtBrokerSessionBeanServicePort"),
                                                                      man.ias.proxy.StmtBrokerSessionBeanService.class,
                                                                      features);
  }
}
