package man.ab.proxy;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebServiceClient(wsdlLocation="http://10.204.6.247:8100/AnggotaBursaSessionBean/AnggotaBursaSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ab.man%2F%7DAnggotaBursaSessionBeanService?wsdl",
  targetNamespace="http://session.ab.man/", name="AnggotaBursaSessionBeanService")
public class AnggotaBursaSessionBeanService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("man.ab.proxy.AnggotaBursaSessionBeanService_Service");
      URL baseUrl =
        AnggotaBursaSessionBeanService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            AnggotaBursaSessionBeanService_Service.class.getResource("http://10.204.6.247:8100/AnggotaBursaSessionBean/AnggotaBursaSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ab.man%2F%7DAnggotaBursaSessionBeanService?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://10.204.6.247:8100/AnggotaBursaSessionBean/AnggotaBursaSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ab.man%2F%7DAnggotaBursaSessionBeanService?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://10.204.6.247:8100/AnggotaBursaSessionBean/AnggotaBursaSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ab.man%2F%7DAnggotaBursaSessionBeanService?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://10.204.6.247:8100/AnggotaBursaSessionBean/AnggotaBursaSessionBeanService/#%7Bhttp%3A%2F%2Fsession.ab.man%2F%7DAnggotaBursaSessionBeanService?wsdl",
          e);
    }
  }

  public AnggotaBursaSessionBeanService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://session.ab.man/", "AnggotaBursaSessionBeanService"));
  }

  public AnggotaBursaSessionBeanService_Service(URL wsdlLocation,
                                                QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="AnggotaBursaSessionBeanServicePort")
  public man.ab.proxy.AnggotaBursaSessionBeanService getAnggotaBursaSessionBeanServicePort()
  {
    return (man.ab.proxy.AnggotaBursaSessionBeanService) super.getPort(new QName("http://session.ab.man/",
                                                                                 "AnggotaBursaSessionBeanServicePort"),
                                                                       man.ab.proxy.AnggotaBursaSessionBeanService.class);
  }

  @WebEndpoint(name="AnggotaBursaSessionBeanServicePort")
  public man.ab.proxy.AnggotaBursaSessionBeanService getAnggotaBursaSessionBeanServicePort(WebServiceFeature... features)
  {
    return (man.ab.proxy.AnggotaBursaSessionBeanService) super.getPort(new QName("http://session.ab.man/",
                                                                                 "AnggotaBursaSessionBeanServicePort"),
                                                                       man.ab.proxy.AnggotaBursaSessionBeanService.class,
                                                                       features);
  }
}
