package man.connect.proxy;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

public class ConnectTSessionBeanServicePortClient
{
  @WebServiceRef
  private static ConnectTSessionBeanService_Service connectTSessionBeanService_Service;

  public static void main(String [] args)
  {
    connectTSessionBeanService_Service = new ConnectTSessionBeanService_Service();
    ConnectTSessionBeanService connectTSessionBeanService = connectTSessionBeanService_Service.getConnectTSessionBeanServicePort();
    // Add your code to call the desired methods.
  }
}
