package man.connect.proxy;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebServiceClient(wsdlLocation="http://10.204.6.247:8100/ConnectTSessionBean/ConnectTSessionBeanService/#%7Bhttp%3A%2F%2Fsession.connect.man%2F%7DConnectTSessionBeanService?wsdl",
  targetNamespace="http://session.connect.man/", name="ConnectTSessionBeanService")
public class ConnectTSessionBeanService_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("man.connect.proxy.ConnectTSessionBeanService_Service");
      URL baseUrl =
        ConnectTSessionBeanService_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ConnectTSessionBeanService_Service.class.getResource("http://10.204.6.247:8100/ConnectTSessionBean/ConnectTSessionBeanService/#%7Bhttp%3A%2F%2Fsession.connect.man%2F%7DConnectTSessionBeanService?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://10.204.6.247:8100/ConnectTSessionBean/ConnectTSessionBeanService/#%7Bhttp%3A%2F%2Fsession.connect.man%2F%7DConnectTSessionBeanService?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://10.204.6.247:8100/ConnectTSessionBean/ConnectTSessionBeanService/#%7Bhttp%3A%2F%2Fsession.connect.man%2F%7DConnectTSessionBeanService?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://10.204.6.247:8100/ConnectTSessionBean/ConnectTSessionBeanService/#%7Bhttp%3A%2F%2Fsession.connect.man%2F%7DConnectTSessionBeanService?wsdl",
          e);
    }
  }

  public ConnectTSessionBeanService_Service()
  {
    super(wsdlLocationURL,
          new QName("http://session.connect.man/", "ConnectTSessionBeanService"));
  }

  public ConnectTSessionBeanService_Service(URL wsdlLocation,
                                            QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ConnectTSessionBeanServicePort")
  public man.connect.proxy.ConnectTSessionBeanService getConnectTSessionBeanServicePort()
  {
    return (man.connect.proxy.ConnectTSessionBeanService) super.getPort(new QName("http://session.connect.man/",
                                                                                  "ConnectTSessionBeanServicePort"),
                                                                        man.connect.proxy.ConnectTSessionBeanService.class);
  }

  @WebEndpoint(name="ConnectTSessionBeanServicePort")
  public man.connect.proxy.ConnectTSessionBeanService getConnectTSessionBeanServicePort(WebServiceFeature... features)
  {
    return (man.connect.proxy.ConnectTSessionBeanService) super.getPort(new QName("http://session.connect.man/",
                                                                                  "ConnectTSessionBeanServicePort"),
                                                                        man.connect.proxy.ConnectTSessionBeanService.class,
                                                                        features);
  }
}
