package man.dsi.proxy;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import man.dsi.proxy.types.ObjectFactory;
import man.dsi.proxy.types.StaticMsg;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 111209.0821.28162)

@WebService(wsdlLocation="http://10.204.6.247:8100/StaticMsgSessionBean/StaticMsgSessionBeanService/#%7Bhttp%3A%2F%2Fsession.dsi.man%2F%7DStaticMsgSessionBeanService?wsdl",
  targetNamespace="http://session.dsi.man/", name="StaticMsgSessionBeanService")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface StaticMsgSessionBeanService
{
  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="getStaticMsgFindByLimitResponse",
    targetNamespace="http://session.dsi.man/", className="man.dsi.proxy.types.GetStaticMsgFindByLimitResponse")
  @RequestWrapper(localName="getStaticMsgFindByLimit", targetNamespace="http://session.dsi.man/",
    className="man.dsi.proxy.types.GetStaticMsgFindByLimit")
  @WebResult(targetNamespace="")
  public List<StaticMsg> getStaticMsgFindByLimit(@WebParam(targetNamespace="",
      name="participantid")
    String participantid);

  @WebMethod
  @Action(input="", output="")
  @ResponseWrapper(localName="updateStaticMsgSetFlagResponse",
    targetNamespace="http://session.dsi.man/", className="man.dsi.proxy.types.UpdateStaticMsgSetFlagResponse")
  @RequestWrapper(localName="updateStaticMsgSetFlag", targetNamespace="http://session.dsi.man/",
    className="man.dsi.proxy.types.UpdateStaticMsgSetFlag")
  @WebResult(targetNamespace="")
  public int updateStaticMsgSetFlag(@WebParam(targetNamespace="", name="participantid")
    String participantid, @WebParam(targetNamespace="", name="extref")
    String extref);
}
