<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://www.mandiri.co.id/services/InvestorAcctStatement"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://www.mandiri.co.id/services/InvestorAcctStatement"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:tns1="http://www.mandiri.co.id/schema/InvestorAcctStatement"
             xmlns:tns2="http://www.mandiri.co.id/schema/KSEI"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <types>
    <xsd:schema targetNamespace="http://www.mandiri.co.id/services/InvestorAcctStatement/types"
                elementFormDefault="qualified">
      <xsd:import schemaLocation="xsd/InvestorAcctStatement.xsd"
                  namespace="http://www.mandiri.co.id/schema/InvestorAcctStatement"/>
    </xsd:schema>
  </types>
  <message name="RequestMessage">
    <part name="part" element="tns1:InvestorAcctStatementRequest"/>
  </message>
  <message name="ResponseMessage">
    <part name="part" element="tns1:InvestorAcctStatementResponse"/>
  </message>
  <portType name="InvestorAcctStatementService">
    <operation name="requestStatement">
      <input message="tns:RequestMessage"/>
      <output message="tns:ResponseMessage"/>
    </operation>
  </portType>
  <binding name="InvestorAcctStatementServiceSOAP11Binding"
           type="tns:InvestorAcctStatementService">
    <soap:binding style="document"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="requestStatement">
      <soap:operation style="document"
                      soapAction="http://www.mandiri.co.id/services/InvestorAcctStatement/requestStatement"/>
      <input>
        <soap:body use="literal" parts="part"/>
      </input>
      <output>
        <soap:body use="literal" parts="part"/>
      </output>
    </operation>
  </binding>
  <service name="InvestorAcctStatementService">
    <port name="InvestorAcctStatementServicePort"
          binding="tns:InvestorAcctStatementServiceSOAP11Binding">
      <soap:address location="http://10.204.6.247:8100/StmtBrokerSessionBean/StmtBrokerSessionBeanService?WSDL"/>
    </port>
  </service>
</definitions>
